// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "source", input: string, result: Array<Source> },
    mutations: never,
    subscriptions: never
};

export interface Source { id: number, title: string, url: string, lang: string }
